### ISSUE TITLE
v0.0.0.74 GUI can't send to multiple addresses, incorrectly reports "insufficient funds"

### ISSUE THREAD

**Issue by walkjivefly** [Crowndev/crown#206]
Tried to send to 4 addresses at once, for a total of 21k with ~22k available:
![Screenshot_2022-11-17_14-39-53](https://user-images.githubusercontent.com/17745270/202467091-a063ac5f-a33d-4792-8ab0-4405b7eaa458.png)

Got this:
![Screenshot_2022-11-17_14-38-10](https://user-images.githubusercontent.com/17745270/202467450-e539292a-6a52-43bf-b098-b5ca16cced15.png)

**Comment by defunctec** [comment]
Confirmed on Linux 22.04.
Attempted from one 51k output

**Comment by BlockMechanic** [comment]
The problem is stemming from where you add a new recipient, you have to select the asset you are sending individually. I have pre-populated the drop down, should be in next version

**Comment by BlockMechanic** [comment]
multi-send send works just fine in GUI, it's console 'sendtomany' that will be a headache

**Comment by walkjivefly** [comment]
Oops, my bad.

If we can pre-populate the dropdown in the GUI why can't we default to crown in the CLI?

**Comment by BlockMechanic** [comment]
I refer to the conversation in dev chat, sending of any coins and assets my be a considered and deliberate action, especially now. Defaulting is always easier , no doubt there but we now have the ability to send things OTHER than CRW. If a user makes a send, they MUST stipulate what to send, otherwise all mistakes will be blamed on developers. The intentional nature of the send operation must remain so prevent users from sending a wrong asset. The nightmare of having sent 500 CRW when you wanted to send 500 BNH is to be avoided, because user will turn around and point at dev and say you defaulted to CRW whereas an ACTIVE choice is user error.

**Comment by defunctec** [comment]
Fixed in 0.75 but now related to #214

**Comment by walkjivefly** [comment]
Confirmed fixed. Thank you.
